"""Create Customer

Revision ID: 1cea238bfd12
Revises: a62e8a1d8579
Create Date: 2023-03-08 15:08:23.602390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cea238bfd12'
down_revision = 'a62e8a1d8579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
