"""Customer

Revision ID: eb8c96e9fea6
Revises: dd71739b7ad8
Create Date: 2023-03-09 11:37:19.502773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8c96e9fea6'
down_revision = 'dd71739b7ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
